# Generated by Django 3.2.5 on 2021-07-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=8, null=True)),
                ('full_address', models.TextField()),
                ('street', models.TextField(editable=False)),
                ('city', models.TextField(editable=False)),
                ('house_number', models.DecimalField(decimal_places=3, editable=False, max_digits=8)),
                ('country', models.TextField(editable=False)),
            ],
        ),
    ]
