# Generated by Django 3.2.5 on 2021-07-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
